### PR TITLE
Switch away from SLD-based export, use a custom exporter instead

### PR DESCRIPTION
**Pull request by brncsk**
Given that SLD support is incomplete in both QGis and MapServer, this PR gets rid of the SLD-based exporter and introduces a new method for exporting vector layer styles into a mapfile. While our exporter is still far from perfect, we believe it already provides a more faithful rendering of complex vector styles than what this plugin currently has to offer (see Figures 1 to 3).

_(The further development of this plugin was sponsored by ViaMap Ltd. in the frame of transferring a municipal GIS system from Intergraph technology to opensource GIS stack. The project was commissioned by the Municipality of 11th District of Budapest, Hungary.)_
#### Support is added for the following features:
- Line Pattern Fills and Point Pattern Fills
- Font Marker symbols
- SVG symbols (also with embedded/linked raster images)
- Line cap and line join styles
- Multi-layer fills and lines
- A subset of SLD well-known markers
#### Other changes introduced by this PR:
- Line widths and symbol sizes are now computed more accurately
- Enhanced labeling (support for partial labels, etc.)
- A more modular approach to the structure of the source code
- Added basic testing facilities and data in form of a PyQgis script and additional infrastructure for running it in a *NIX environment.
- Options for labeling (_Force_ and _Partials_) were removed from the _Advanced_ tab. The same effect can be achieved by using the following settings:
  - `FORCE` is enabled by checking the _Labels → Rendering → Show all labels..._ checkbox in _Layer Settings_ (See Figure 4).
  - `PARTIALS` is enabled by checking the _Show partial labels_ checkbox in the _Automated placement settings_ dialog box (available by clicking the button in the upper right corner of the _Label_ tab in _Layer Settings_; see Figure 5). (Please note that as this setting is applied to all layers in QGis it also will be applied to all layers in the mapfile.)
#### Our approach also has a couple of shortcomings:
- As the value of the `SIZEUNITS` setting can only be set per-layer in a mapfile (as opposed to a per-style-attribute approach in QGis), we use millimeters as the default size unit and switch if and only if the layer has a style attribute with "Map unit" set as its unit.
- Lots of symbol layer styles and style attributes are unsupported at the moment.
#### Images for visual comparison:

**Fig. 1.** – Original QGis project:

QGis

**Fig. 2.** – Mapfile exported by the plugin in its current form:

Original plugin

**Fig. 3.** – Mapfile exported by the plugin version in this proposed PR:

Proposed PR

**Fig. 4.** – Enabling `FORCE` in the mapfile:

Enabling FORCE in the mapfile

**Fig. 5.** – Enabling `PARTIALS` in the mapfile:

Enabling PARTIALS in the mapfile

### CODE REVIEW

**Comment by luipir** [comment]
Hi, I just come back from holidays and I hadn't time to check and run the code... it's a really interesting add to the plugin.

As I understand, this patch, give a way to select an alternative way to export mapfile leaving old methods available. Is it correct?

regards,

**Comment by brncsk** [comment]
Hi,
no, this branch currently only uses our new method for exporting vector layer styles (where layer.type() == QgsLayer.VectorLayer, see MapfileExporter.py line 219), so the old, SLD-based method is removed from the code. However I can modify our code to offer both options (the old SLD-based export and our new method) and let the user select between them (e. g. by clicking a checkbox on the GUI).

**Comment by luipir** [comment]
I agree that would be present the most completed method, but map styling is so complex and with a so wide use cases that could be more safe leaving the sld use in case the user need some feature that are not covered by the other method (sorry I'm talking without testing it, but I suggested to test it to some power users).
Other interesting use case is when the an advanced mapserver user create two mapfiles with different method and merge them manually.
So my opinion is to allow export method selection and leave the old code available.
This can also facilitate passing from a method to another for users that use this plugin in production context. They don't have to manage an old version of the plugin in case they feel safe with the sld method.
You proposal to leave the old code and add a checkbox for export method selection is ok for me.

**Comment by luipir** [comment]
news?

**Comment by brncsk** [comment]
Luigi, I am really sorry for not getting back to you earlier – it's been a busy week (beginning of the academic year) and a hardware problem also rendered my laptop completely unusable. I do plan to make the changes we agreed on though, I hope to finish it by the end of next week. Sorry for the inconvenience!

**Comment by luipir** [comment]
no problem :)

**Comment by brncsk** [comment]
So I finally had the time to implement the changes :).
Now there are a pair of radio buttons at the bottom in the General tab for choosing between the original export method and the new one. I also added a "Help me decide" link which shows a message box explaining the pros and cons of both methods. The user's choice is stored in a QSettings key ('/rt_mapserver_exporter/useSLD') and the appropriate radio is checked the next time the window is opened.

**Comment by aperi2007** [comment]
Hi, I try the new version of plugin.
Downloaded it from this url:
https://github.com/brncsk/rt_mapserver_exporter/archive/master.zip

Try it on a qgis 2.10 (32bit) on windows 7.
The qgis is installed using the offline installer.

When try to opne the plugin it dont start.
The console python messages windows report this messages.
Some of them are to other plugins. I dont understand if something if from the "rt_mapserver_exporter".

2015-09-27T07:28:35 1 warning:C:\PROGRA~2\QGISPI~1\apps\Python27\lib\site-packages\PyQt4\uic\uiparser.py:890: PendingDeprecationWarning: This method will be removed in future versions. Use 'elem.iter()' or 'list(elem.iter())' instead.

for include in elem.getiterator("include"):

traceback: File "<string>", line 1, in <module>

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\pyplugin_installer\installer.py", line 47, in initPluginInstaller

pluginInstaller = QgsPluginInstaller()

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\pyplugin_installer\installer.py", line 63, in **init**

plugins.getAllInstalled()

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\pyplugin_installer\installer_data.py", line 715, in getAllInstalled

plugin = self.getInstalledPlugin(key, path=path, readOnly=readOnly, testLoad=testLoadThis)

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\pyplugin_installer\installer_data.py", line 623, in getInstalledPlugin

pkg.classFactory(iface)

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python/plugins\MetaSearch__init__.py", line 28, in classFactory

from MetaSearch.plugin import MetaSearchPlugin

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import

mod = _builtin_import(name, globals, locals, fromlist, level)

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python/plugins\MetaSearch\plugin.py", line 31, in <module>

from MetaSearch.dialogs.maindialog import MetaSearchDialog

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import

mod = _builtin_import(name, globals, locals, fromlist, level)

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python/plugins\MetaSearch\dialogs\maindialog.py", line 49, in <module>

from MetaSearch.dialogs.manageconnectionsdialog import ManageConnectionsDialog

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import

mod = _builtin_import(name, globals, locals, fromlist, level)

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python/plugins\MetaSearch\dialogs\manageconnectionsdialog.py", line 39, in <module>

BASE_CLASS = get_ui_class('manageconnectionsdialog.ui')

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python/plugins\MetaSearch\util.py", line 63, in get_ui_class

return loadUiType(ui_file_full)[0]

File "C:\PROGRA~2\QGISPI~1\apps\Python27\lib\site-packages\PyQt4\uic__init__.py", line 210, in loadUiType

winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix)

File "C:\PROGRA~2\QGISPI~1\apps\Python27\lib\site-packages\PyQt4\uic\Compiler\compiler.py", line 139, in compileUi

w = self.parse(input_stream, resource_suffix)

File "C:\PROGRA~2\QGISPI~1\apps\Python27\lib\site-packages\PyQt4\uic\uiparser.py", line 992, in parse

actor(elem)

File "C:\PROGRA~2\QGISPI~1\apps\Python27\lib\site-packages\PyQt4\uic\uiparser.py", line 890, in readResources

for include in elem.getiterator("include"):

2015-09-27T07:28:36 1 warning:C:/PROGRA~2/QGISPI~1/apps/qgis/./python\qgis\utils.py:478: ImportWarning: Not importing directory 'C:/Users/andrea/.qgis2/python/plugins\qsphere\xml': missing **init**.py

mod = _builtin_import(name, globals, locals, fromlist, level)

traceback: File "<string>", line 1, in <module>

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\pyplugin_installer\installer.py", line 47, in initPluginInstaller

pluginInstaller = QgsPluginInstaller()

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\pyplugin_installer\installer.py", line 63, in **init**

plugins.getAllInstalled()

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\pyplugin_installer\installer_data.py", line 715, in getAllInstalled

plugin = self.getInstalledPlugin(key, path=path, readOnly=readOnly, testLoad=testLoadThis)

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\pyplugin_installer\installer_data.py", line 623, in getInstalledPlugin

pkg.classFactory(iface)

File "C:/Users/andrea/.qgis2/python/plugins\qsphere__init__.py", line 4, in classFactory

from qsphere import MainPlugin

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import

mod = _builtin_import(name, globals, locals, fromlist, level)

File "C:/Users/andrea/.qgis2/python/plugins\qsphere\qsphere.py", line 11, in <module>

import doUI

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import

mod = _builtin_import(name, globals, locals, fromlist, level)

File "C:/Users/andrea/.qgis2/python/plugins\qsphere\doUI.py", line 5, in <module>

from ViewerHelp import Ui_Dialog

File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import

mod = _builtin_import(name, globals, locals, fromlist, level)

File "C:/Users/andrea/.qgis2/python/plugins\qsphere\ViewerHelp.py", line 15, in <module>

import xml.etree.ElementTree as ET

Regards.

**Comment by luipir** [comment]
seems more related with some local problem of your installation and not related with the plugin. Please do these tests:
1) start qgis with --noplugins
2) check if qgis works
2.1) check if plugin manager works correctly
3) do a copy of you c:\Users<your user>.qgis2\python\plugins somewhere outside the .qgis2\python path
4) create an empty c:\Users<your user>.qgis2\python\plugins path
5) reinstall the rt_mapserve_exporter plugin in the clean dir
6) test if the problem is still there

**Comment by aperi2007** [comment]
Hi,

I do all step .

After try-ing newly the RT_MapServer , I have this other error :+1: 

<pre>
An error has occured while executing Python code:
Traceback (most recent call last):
  File "C:/Users/andrea/.qgis2/python/plugins\rt_mapserver_exporter\plugin.py", line 65, in run
    from .mapfileexportdlg import MapfileExportDlg
  File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/andrea/.qgis2/python/plugins\rt_mapserver_exporter\mapfileexportdlg.py", line 31, in 
    import MapfileExporter
  File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/andrea/.qgis2/python/plugins\rt_mapserver_exporter\MapfileExporter.py", line 9, in 
    from utils import *
  File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/andrea/.qgis2/python/plugins\rt_mapserver_exporter\utils.py", line 1, in 
    import mapscript
  File "C:/PROGRA~2/QGISPI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named mapscript
Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]
QGIS version:
2.10.1-Pisa Pisa, d20c5b7
Python path: ['C:/PROGRA~2/QGISPI~1/apps/qgis/./python/plugins\\processing', 'C:/PROGRA~2/QGISPI~1/apps/qgis/./python', u'C:/Users/andrea/.qgis2/python', u'C:/Users/andrea/.qgis2/python/plugins', 'C:/PROGRA~2/QGISPI~1/apps/qgis/./python/plugins', 'C:\\PROGRA~2\\QGISPI~1\\bin\\python27.zip', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~2\\QGISPI~1\\bin', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win32.egg', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib\\site-packages\\python_dateutil-2.2-py2.7.egg', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib\\site-packages\\pytz-2014.2-py2.7.egg', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win32.egg', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib\\site-packages\\six-1.6.1-py2.7.egg', 'C:\\PROGRA~2\\QGISPI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', u'C:/Users/andrea/.qgis2//python', 'C:\\PROGRA~2\\QGISPI~1\\apps\\qgis\\python\\plugins\\fTools\\tools', 'D:/0_dropbox_store/Dropbox/progetti/progetto-pedologia/DBPedologico']
</pre>

Unfortunately my qgis come from a offline setup file and has not mapscript available.

I must retry it using the dev version of qgis.

**Comment by luipir** [comment]
the laste error doe not depend on the plugin but your local installation... please notify only plugin related errors

**Comment by aperi2007** [comment]
Hi move to the qgis-dev and retry .

Now have this error:

<pre>
2015-10-01T21:23:11 1   Traceback (most recent call last):
              File "C:/Users/andrea/.qgis2/python/plugins\rt_mapserver_exporter\mapfileexportdlg.py", line 147, in accept
                legend = self.legend
              File "C:/Users/andrea/.qgis2/python/plugins\rt_mapserver_exporter\MapfileExporter.py", line 231, in export
                Serialization.VectorLayerStyleSerializer(layer, msLayer, msMap)
              File "C:/Users/andrea/.qgis2/python/plugins\rt_mapserver_exporter\Serialization.py", line 126, in __init__
                self.serializeCategorizedSymbolRenderer(renderer)
              File "C:/Users/andrea/.qgis2/python/plugins\rt_mapserver_exporter\Serialization.py", line 162, in serializeCategorizedSymbolRenderer
                SymbolLayerSerializer(renderer.symbols()[i], msClass, self.msLayer, self.msMap)
            TypeError: QgsCategorizedSymbolRendererV2.symbols(QgsRenderContext): not enough arguments
            
</pre>

**Comment by aperi2007** [comment]
Hi, the author of this PULL evolution for RT_MapServer_Exporter please could contact me separately at this email:

andrea.peri@regione.toscana.it

I need some explain about your need of fisclaimer and what kind of disclaimer you need to apply.

The Plugin is owned by Tuscany Region that fund the realization of it. 
The plugin is surely a piece of gfoss software so every contribute is really welcome , but we need to preserve our disclamers and need to reject every disclaimer that is in in conflict with ours.

I dont know if and where your disclaimers could change the code.
So please report me every disclaimer that you plan to apply to this plugin and the section where it will be applied.

Thx.

**Comment by brncsk** [comment]
Hi, Andrea!

I am the developer of this pull request. As far as I can understand, you are concerned with the fact that I, in my original comment, mentioned that the development of this pull request was funded by ViaMap Ltd. We absolutely acknowledge the fact that the original development of this plugin is funded by Tuscany Region and we value all your resources that went into the realiztation of this great piece of software. Also, we would never remove or modify any disclaimer in the source code that points to these facts. (Actually, no author/license information is modified by this pull request whatsoever.) However, (if and only if this PR gets merged), we would happily accept a short reference to ViaMap Ltd. somewhere in the source code, if you agree and in a form that is acceptable to you and other contributors. As this decision may affect other people and also the source code of the plugin itself, I prefer that we discuss the matter openly here. However if you want, you may contact me at adam.barancsuk (at) viamap.hu.

I also noticed that there is a header in the original python source files containing author and license information. I realize that this information is absent from the files that are introduced by this PR (most importantly including but not limited to `MapfileExporter.py`, `Serialization.py` and `SerializationUtils.py`). I am absolutely willing to add this header information to those files though.

As for the three Python-related problems you experienced:
- The first one is completely unrelated to this plugin, as Luigi has already mentioned.
- The second one (`ImportError: No module named mapscript`) can be solved by installing the `mapscript-python` package from the OSGeo4W installer. (This package is however not a new dependency but one that was already needed by older versions of this plugin.)
- As for the third error, it is caused by the API changes between the stable and development versions of QGIS. As the API is subject to further changes until the next QGIS version is released<sup>1</sup>, I prefer to adapt to these once they are stabilized.

Regards,
Ádám Barancsuk

<sup>1</sup>The next release is expected on the 23rd of October (see http://blog.qgis.org/2015/09/26/feature-freeze-is-now-in-effect-for-qgis-2-12/)

**Comment by luipir** [comment]
I agree with Ádám,

I also prefer that topics related with merging/forking and disclaiming remain public.
In my point of view the solution proposed by Ádám is rasonable and accettable. 

@brncsk please add you as co-author in the comments updating PR... I think it is a correct and simpler for code readers than using git blame

**Comment by aperi2007** [comment]
Hi, it is ok for me.
Also I test your patch on a qgis 2.10.
It work well for me.

Thx for your patch.

**Comment by aperi2007** [comment]
Hi, I notice this change betweeen the qgis project and the mapfile:

In the qgis project there is a layer with a label having a font-name and a font-style.

See the image:

tuffy

But in the mapfile it is changed in:
      LABEL
        FONT "Tuffy-Normal"
        SIZE 21
        BUFFER 5
        ENCODING "utf-8"
        OFFSET 0 0
        POSITION AUTO
        PRIORITY 5
        SHADOWSIZE 1 1
      END # LABEL

Naming it as "Tuffy-Normal"
so the mapserver don't find it.

Regards.

Andrea.

**Comment by luipir** [comment]
Hi Andrea, this is related wit the patch or happen also withe the traditianal stable branch of the plugin? it seems an otion not related with the Ádám pull request. Am I correct?

**Comment by aperi2007** [comment]
I dont know if this is due at the adam patch or not.
Surely Adam could understand if yes.

Another issu I notice.
That in the setting of the label the rt_mapserver will output many settings thats need to have the 
layer level setting: LABELCACHE ON

but this is missing in the output of the rt_mapserver_export.

**Comment by aperi2007** [comment]
I test the late version patched with an out project,
but seem that the label part was not working absolutely.
I'm try to understand why and what is wrong.
The two issu I report previously are what I find at now as missing to have a correctly work mapfile.
I dont know if it is an adam patch issue or not.

However I guess there is something else.
Because actually the label are visible only in a too few features in the output of the mapfile.

I could not test the original code because it was simply unable to generate an acceptable mapfile from a complex qgis project like the one I'm using for the test.

If Adam is interested in other report please ask me to.

However the plugin with the Adam patch is surely better rather than the original one.

**Comment by aperi2007** [comment]
Hi,
I found the issue.
:)

My qgis project has a layer rendered using a categorize rendering and a Layer enabled.

The translation in a mapserver mapfile is done creating many CLASS elements. One for every domain in the qgis style domain render.
One for every domain of the categorized render in qgis.

This is correctly done in the Adam patch, 
but put the settings for the LABEL only in the first CLASS element and leave the other class elements without the LABEL definition.

AlsoI I notice that in the LABEL definition is seem to do a wrong font size .
Infact in the qgis project the label was 9 dot size, instead in the LABEL element in the qgis project is is 21 size label.

Regards.

Andrea.

**Comment by luipir** [comment]
Yes definetively I've to merge and deliver the new plugin, so we can follow an ordered issue generation. Take patient, I just started working for Boundless and I'm really busy.

In two weeks I'll be to the Hackmeeting in Gran Canaria, there I'll prepare the new rlease for sure. Please @brncsk check if issues reported by Andrea can be solved, so I can be merge a more cleaned patch. If you don't have time now, I will merge dureing Hackmeeting.

regards

**Comment by aperi2007** [comment]
Hi,
just the remenber,
I do a look at the file templtae generated by the plugin.
The template is used from mapserver to create an html response at a getfeatureinfo.

I notice thata the "name" of the layers referred in the template are not corresponding to the same name in the mapfile :
This is the NAME in the mapfile for a layer generated by the plugin:

```
NAME "Capacita' d'uso e fertilita' dei suoli"
```

And this is the correspondin name in the html template generated by the plugin:

[resultset layer="LCC20150527185055031"]
<b>"Capacita' d'uso e fertilita' dei suoli"</b>

The correct string should be:
[resultset layer="Capacita' d'uso e fertilita' dei suoli"]

Regards,

A.

**Comment by luipir** [comment]
please Andrea... opene a separate tiket NOT here in this thread! and for sure, this is a tiket related with the old part of the plugin not related with @brncsk pull request. BE ORDERED please!

**Comment by aperi2007** [comment]
Hi, I have no chance to test with old plugin.
If you are sure for this I could put the ticket in the old plugin.
But I'm not so sure.
I don't remenber this issue when the code was tested.
Unfortunately I have no time to test the old plugin.
I dedicate more than 8 hours to test this patch, and explore the issues.
Is too much time.

regards.

**Comment by brncsk** [comment]
Hi!

I finally had the time to work on the problems described by @aperi2007. (Thanks for the quite thorough testing, even though this is certainly not the best place for bug reports. I hope @luipir can finally merge this and then we can move on to accepting issues as normal.)

In no particular order I came to the following conclusions and made the following changes:
- Yes, the `LABEL` element should be emitted for all `CLASS`es in a layer (most importantly in the case of graduated and categorized symbols). This is now fixed. I also added tests for this. (I also fixed a couple of bugs in the testing scripts.)
- `LABELCACHE ON` by default on all layers – this is on by default, at least that's what the mapserver documentation[1] says. Do you observe any differences in rendering when this property is explicitly set to `ON` in the mapfile?
- Font names being emitted as `<fontname>-Normal` instead of just `<fontname>`: As far as I know, MapServer does not automatically resolve font names into font files, so we can name fonts however we want in the mapfile as long as we assign a font file to that name in `FONTSET`. As I understand however, you have some sort of mechanism that automatically assigns font names to font files. May I ask what platform are you on (Linux/Windows/etc.) and which version of MapServer do you use? Do you have a vendor-provided default `FONTSET` or is it custom generated? For the time being, I changed the plugin's behavior to emitting just `<fontname>` as it is harmless.
- As for the font size: QGis defines a font's size in _points_. MapServer expects a font's size to be in _pixels._ These are sadly not the same (even though the old behavior of the plugin was to treat points as pixels). I spent quite some time researching how a font definition's pixel size can be inferred from its point size in Qt. Without going into too much detail, I found no trivial solution but concluded that the best way is the one I'm using right now, so I'd rather not change it. (I also found this to provide a more faithful rendering than the old plugin's rather small font sizes.)
- Thank you for the pull request you sent, @aperi2007! Even though I'm reluctant to merge all of it (some of your changes are opinion-based and/or caters for your specific use case only), I incorporated two of the changes into this PR: the one adding layer-level metadata fields and the one that uses `layer.name()` instead of `layer.id()` in the template. I could not cherry-pick these changes as they were bundled with other stuff I did not want to merge, but I did mention you in the respective commit messages!
- I added myself as a contributor in `metadata.txt` and also mentioned ViaMap in there.
- I fixed a couple of bugs related to the QGIS 2.12 changes.

Luigi, If there is anything else I can do to get this merged, please let me know!

[1] http://mapserver.org/mapfile/layer.html

**Comment by luipir** [comment]
Hi Adam

you can do anything... My plan is to merge during this hackmeeting... and going deeply in your sld management to understand your innovation.

Probably I will need your support... it's only useful to understand the philosophy of the code. It's not a requirement to merge. The code seems already well tested.

thank you for this contribution

**Comment by aperi2007** [comment]
Hi Adam,
Hi Luigi.

I have forked the plugin and start to change it as need for our internel use.

Unfortunatelly, I have done a PULL to the Adam reposity.
After this.
I see every other change is pulled automatically to the adam reposity.

I need to apply man other changes ,
all forour need internal of course.
Many of thema as setting hardcoded usefl for us.
Like our Regional Logo, Disclaiamers, and so on.
All need not usful for no one.

So I like to stop the automatic pull forward the adam repository.

Is this possible ?
I don't know how do this.

**Comment by luipir** [comment]
please Andrea, wait the merge and we can work on a common code base.

I'll publish the plugin as NOT experimental... because of your an Adam tests. A common user that don't want to use Adam fuctioanlities can continue using the plugin as before.

**Comment by brncsk** [comment]
Ok, this is great! I can answer any questions about the new code, if you
ask.

**Comment by luipir** [comment]
published in qgis repo as 0.5.0 version

http://plugins.qgis.org/plugins/rt_mapserver_exporter/version/0.5.0/

thank you Ádám

**Comment by luipir** [comment]
Hi @brncsk a quick question
first: sorry I don't have othere way to communicate with you, I don't have you contact

The question is:
Reading the code I can see you skipped SLD and generated mapfile starting directly from renderer serialization. My question is, did you evaluate to apply visitor pattern to the qgis QML?

The reason of the question is:
I'm evaluating the best way to export QML to SLD 1.0  (because of geoserver contraints)

thank you for every answer

Cheers

P.S. we can continue out of this PR: please write me to luipir AT gm..l DOT com

**Pull request merged**
